apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      initContainers:
        - name: wait-for-postgres

          image: postgres:17

          command:
            - sh
            - -c
            - |
              until pg_isready -h user-db -p 5432 -U user_service_app; do
                echo "Waiting for postgres..."
                sleep 2
              done

      containers:
        - name: user-service

          image: user-service:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: USER_DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: USER_DB_PASSWORD

          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3