apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-db

  template:
    metadata:
      labels:
        app: order-db

    spec:
      containers:
        - name: postgres

          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: order_service

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ORDER_DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ORDER_DB_PASSWORD