apiVersion: v1
kind: Secret
metadata:
  name: app-secret-example

type: Opaque

stringData:
  AUTH_DB_USERNAME: CHANGE_ME
  AUTH_DB_PASSWORD: CHANGE_ME

  USER_DB_USERNAME: CHANGE_ME
  USER_DB_PASSWORD: CHANGE_ME

  ORDER_DB_USERNAME: CHANGE_ME
  ORDER_DB_PASSWORD: CHANGE_ME

  PAYMENT_DB_USERNAME: CHANGE_ME
  PAYMENT_DB_PASSWORD: CHANGE_ME

  JWT_SECRET_KEY: CHANGE_ME