apiVersion: v1
kind: Secret
metadata:
  name: app-secret

type: Opaque

stringData:
  AUTH_DB_USERNAME: "auth_service_app"
  AUTH_DB_PASSWORD: "auth_service_pass"

  USER_DB_USERNAME: "user_service_app"
  USER_DB_PASSWORD: "user_service_pass"

  ORDER_DB_USERNAME: "order_service_app"
  ORDER_DB_PASSWORD: "order_service_pass"

  PAYMENT_DB_USERNAME: "payment_service_app"
  PAYMENT_DB_PASSWORD: "payment_service_pass"

  JWT_SECRET_KEY: "mySuperSecretKeymySuperSecretKeymySuperSecretKey"