apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8085

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET_KEY

            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL

            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_URL

            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_SERVICE_URL

            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_URL

          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            periodSeconds: 10
            failureThreshold: 3